name: Fetch Latest Blogs

on:
  schedule:
    - cron: '0 0 * * *'  # This will run the action daily
  workflow_dispatch:  # You can manually trigger the workflow too

jobs:
  fetch-blogs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Fetch latest blog posts from Hashnode
      run: |
        # Set the Hashnode API URL and your username
        HASHNODE_USERNAME="thewood"
        HASHNODE_API="https://api.hashnode.com/"
        
        # Query to fetch the latest 4 blog posts
        QUERY='{
          "query": "{user(username: \"'$HASHNODE_USERNAME'\") {publication {posts(page: 0, limit: 4) {title slug}}}}"
        }'
        
        # Fetch data from Hashnode API
        response=$(curl -s -X POST $HASHNODE_API -H "Content-Type: application/json" -d "$QUERY")
        
        # Extract the latest 4 posts
        posts=$(echo $response | jq -r '.data.user.publication.posts | map("* [\(.title)](https://thewood.hashnode.dev/post/\(.slug))") | join("\n")')

        # Insert posts into the README file
        sed -i "/<!-- BLOG-POST-LIST:START -->/,+1c\\
<!-- BLOG-POST-LIST:START -->\n$posts\n<!-- BLOG-POST-LIST:END -->" README.md

    - name: Commit updated README
      uses: EndBug/add-and-commit@v7
      with:
        author_name: 'GitHub Actions'
        author_email: 'actions@github.com'
        message: 'Update latest blog posts'
