name: Fetch Latest Hashnode Blog Posts

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: 

jobs:
  update-readme:
    name: Update README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Ensure README.md exists
        run: |
          if [ ! -f README.md ]; then
            echo "# README" > README.md
          fi

      - name: Fetch Hashnode Blog Posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "HASHNODE_BLOG"
          feed_list: "https://thewood.hashnode.dev/rss.xml"
          template: |
            <tr>
              <td>
                <a href="$url">
                  <img src="$image" alt="$title" width="100%">
                </a>
              </td>
              <td>
                <a href="$url">
                  <strong>$title</strong>
                </a>
                <br>
                <em>Published on $date</em>
                <br>
                $description
              </td>
            </tr>
          date_format: "mmm dd, yyyy"
          max_post_count: 4

      - name: Commit and Push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Update README with latest Hashnode blog posts"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
