name: Fetch Latest Blogs

on:
  push:
    branches:
      - main  # Trigger when pushing to the main branch
  workflow_dispatch:  # Manually triggerable
  schedule:
    - cron: "0 * * * *"  # Run every hour (adjust the cron timing if needed)

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install requests
        run: pip install requests

      - name: Fetch Latest Blog Posts
        run: |
          python fetch_latest_blogs.py
          
      - name: Commit updated README
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Update README with latest blog posts"
          git push
